import { firstDayOfNextMonth, trimDecimalPoints } from '../../../utils/utils'

/**
* Calculate the average of values in an array
* @example
*   average( [ 4, 4, 5, 6, 6 ] ) // 5
* @param {Array} arr - An array of integers or floats
* @returns {number}
*/
const average = arr => arr.reduce((p, c) => p + c, 0) / arr.length

/**
* Parse the data for monthly balance graph. This function refill the empty data of every month and do an average of repeated months.
* @requires firstDayOfNextMonth
* @example
*   const data = [{"balance": 0,"date": "2014-11-01"},{"balance": 678.74,"date": "2014-12-01"},{"balance": 800.75,"date": "2015-01-01"},{"balance": 1189.88,"date": "2015-01-01"},{"balance": 8110.37,"date": "2015-03-01"}];
*   parseDataForGraph(data) // [ { date: '2014-11-01', balance: 0 }, { date: '2014-12-01', balance: 678.74 }, { date: '2015-01-01', balance: 995.32 }, { date: '2015-02-01' }, { date: '2015-03-01', balance: 8110.37 } ]
* @param {Array.<Object>} data - An array of objects (the object must contain a date property. The array must be ordered in date ascendant)
* @param {string} data.date - A valid date with this format '2018-03-01'. It is very important that all dates are on the first day of the month
* @param {float|integer} data.balance
* @returns {Array.<Object>}
*/
function parseDataForGraph(data = []) {
	if (!data.length) {
		return []
	}

	// Get all dates in original data avoiding repeated information and refill with the missing dates
	const firstDate = data[0].date
	const lastDate = data[data.length - 1].date

	const listOfAllDates = [firstDate]
	while (listOfAllDates[listOfAllDates.length - 1] !== lastDate) {
		const nextMonth = firstDayOfNextMonth(listOfAllDates[listOfAllDates.length - 1])
		if (!listOfAllDates.includes(nextMonth)) {
			listOfAllDates.push(nextMonth)
		}
	}

	// For each date, calculate the balance.
	// A date should not necessarily have a balance. If exist more than one balance for the same month, do an average.
	const result = []
	listOfAllDates.forEach(date => {
		const monthlyData = {
			date: date
		}

		let allBalancesOnThisMonth = []
		data.forEach(d => {
			if (d.date === date) {
				allBalancesOnThisMonth.push(d.balance)
			}
		})

		if (allBalancesOnThisMonth.length) {
			const averagedBalanced = average(allBalancesOnThisMonth) || 0
			monthlyData.balance = parseFloat(averagedBalanced.toFixed(2))
		}

		result.push(monthlyData)
	})

	return result
}

/**
 * If receive at least 12 months of already parsed monthly balance for graph, return the data of last year. 
 * @requires parseDataForGraph
 * @param {Object[]} [dataParsedForGraph=[]] - Array of objects generated by parseDataForGraph function
 * @param {string} dataParsedForGraph[].date - A valid date with this format '2018-03-01'
 * @param {float|integer} [dataParsedForGraph[].balance] - Amount of balance
 * @param {number} [months=12] - Number of months to return. Default is 12.
 * @returns {Array.<Object>|Array}
 */
function getLastMonthsData(dataParsedForGraph = [], months = 12) {
	if (!Array.isArray(dataParsedForGraph) || dataParsedForGraph.length < months) {
		return []
	}

	return dataParsedForGraph.slice(Math.max(dataParsedForGraph.length - months, 0))
}


/**
 * Returns the last five years from the year received as argument
 * @param {number} year
 * @returns {Array.number}
 */
const getLastFiveYearsFrom = (year) => {
	const maxYearsNumber = 5
	const result = []

	for (let iteration = 0; iteration < maxYearsNumber; iteration++) {
		result.push(year - iteration)
	}

	return result
}

/**
 * Calculate the net balance change (last - first) from an array of monthly data entries.
 * Entries without a balance property are filtered out.
 * @requires trimDecimalPoints
 * @param {Object[]} [data=[]] - Array of objects with optional balance property
 * @param {string} data[].date - Date in 'YYYY-MM-DD' format
 * @param {float} [data[].balance] - Monthly balance amount
 * @returns {number|null} The differential rounded to 2 decimals, or null if <2 entries with balance
 */
const computeDifferential = (data = []) => {
	const entriesWithBalance = data.filter(entry => entry.balance !== undefined)

	if (entriesWithBalance.length < 2) {
		return null
	}

	const first = entriesWithBalance[0].balance
	const last = entriesWithBalance[entriesWithBalance.length - 1].balance
	const diff = last - first

	return trimDecimalPoints(diff)
}

/**
 * Format a number to a Euro string with 2 decimals using dot as decimal separator.
 * @example
 *   formatDifferential(3140.26) // '+ 3140.26 €'
 *   formatDifferential(-1200.50) // '- 1200.50 €'
 *   formatDifferential(0) // '0 €'
 * @param {number|null|undefined} value - Numeric value to format
 * @returns {string} Formatted Euro string
 */
const formatDifferential = (value) => {
	if (value === null || value === undefined || Number.isNaN(value)) {
		return '0 €'
	}

	if (value === 0) {
		return '0 €'
	}

	const absValue = Math.abs(value)
	const sign = value > 0 ? '+ ' : '- '
	const formatted = absValue % 1 === 0 ? absValue : absValue.toFixed(2)

	return `${sign}${formatted} €`
}

export {
	parseDataForGraph,
	getLastMonthsData,
	getLastFiveYearsFrom,
	computeDifferential,
	formatDifferential,
}
