import { trimDecimalPoints } from '../../../utils/utils'
import { formatMonth, monthKey, nextMonth } from '../../../utils/months'

/**
* Parse the monthly balances for the graph: one point per month from the first to the last balance, refilling the months without balance.
* @requires monthKey
* @requires nextMonth
* @requires formatMonth
* @example
*   const data = [{ year: 2014, month: 'DECEMBER', balance: 678.74 }, { year: 2015, month: 'FEBRUARY', balance: 0 }]
*   parseDataForGraph(data) // [ { key: '2014-12', label: 'December 2014', balance: 678.74 }, { key: '2015-01', label: 'January 2015' }, { key: '2015-02', label: 'February 2015', balance: 0 } ]
* @param {Array.<Object>} data - Ordered ascending by year and month, one entry per month
* @param {number} data.year
* @param {string} data.month - A Month enum value, e.g. 'JANUARY'
* @param {float|integer} data.balance
* @returns {Array.<Object>}
*/
function parseDataForGraph(data = []) {
	if (!data.length) {
		return []
	}

	const balancesByKey = new Map(data.map(monthlyBalance => [monthKey(monthlyBalance), monthlyBalance.balance]))
	const lastKey = monthKey(data[data.length - 1])

	const result = []
	let current = { year: data[0].year, month: data[0].month }
	let key = monthKey(current)
	while (key <= lastKey) {
		const point = { key, label: formatMonth(current) }
		if (balancesByKey.has(key)) {
			point.balance = parseFloat(balancesByKey.get(key).toFixed(2))
		}
		result.push(point)

		current = nextMonth(current)
		key = monthKey(current)
	}

	return result
}

/**
 * If receive at least 12 months of already parsed monthly balance for graph, return the data of last year. 
 * @requires parseDataForGraph
 * @param {Object[]} [dataParsedForGraph=[]] - Array of objects generated by parseDataForGraph function
 * @param {string} dataParsedForGraph[].key - Sortable month key, e.g. '2018-03'
 * @param {string} dataParsedForGraph[].label - Month shown to the user, e.g. 'March 2018'
 * @param {float|integer} [dataParsedForGraph[].balance] - Amount of balance
 * @param {number} [months=12] - Number of months to return. Default is 12.
 * @returns {Array.<Object>|Array}
 */
function getLastMonthsData(dataParsedForGraph = [], months = 12) {
	if (!Array.isArray(dataParsedForGraph) || dataParsedForGraph.length < months) {
		return []
	}

	return dataParsedForGraph.slice(Math.max(dataParsedForGraph.length - months, 0))
}


/**
 * Returns the last five years from the year received as argument
 * @param {number} year
 * @returns {Array.number}
 */
const getLastFiveYearsFrom = (year) => {
	const maxYearsNumber = 5
	const result = []

	for (let iteration = 0; iteration < maxYearsNumber; iteration++) {
		result.push(year - iteration)
	}

	return result
}

/**
 * Calculate the net balance change (last - first) from an array of monthly data entries.
 * Entries without a balance property are filtered out.
 * @requires trimDecimalPoints
 * @param {Object[]} [data=[]] - Array of objects with optional balance property
 * @param {string} data[].key - Sortable month key, e.g. '2018-03'
 * @param {float} [data[].balance] - Monthly balance amount
 * @returns {number|null} The differential rounded to 2 decimals, or null if <2 entries with balance
 */
const computeDifferential = (data = []) => {
	const entriesWithBalance = data.filter(entry => entry.balance !== undefined)

	if (entriesWithBalance.length < 2) {
		return null
	}

	const first = entriesWithBalance[0].balance
	const last = entriesWithBalance[entriesWithBalance.length - 1].balance
	const diff = last - first

	return trimDecimalPoints(diff)
}

/**
 * Format a number to a Euro string with 2 decimals using dot as decimal separator.
 * @example
 *   formatDifferential(3140.26) // '+ 3140.26 €'
 *   formatDifferential(-1200.50) // '- 1200.50 €'
 *   formatDifferential(0) // '0 €'
 * @param {number|null|undefined} value - Numeric value to format
 * @returns {string} Formatted Euro string
 */
const formatDifferential = (value) => {
	if (value === null || value === undefined || Number.isNaN(value)) {
		return '0 €'
	}

	if (value === 0) {
		return '0 €'
	}

	const absValue = Math.abs(value)
	const sign = value > 0 ? '+' : '-'
	const formatted = absValue % 1 === 0 ? absValue : absValue.toFixed(2)

	return `${sign}${formatted} €`
}

export {
	parseDataForGraph,
	getLastMonthsData,
	getLastFiveYearsFrom,
	computeDifferential,
	formatDifferential,
}
